site_name: おやさいサーバー Wiki
site_url: https://wiki.oyasai.io/
docs_dir: docs

theme:
  name: material
  language: ja
  features:
    - navigation.indexes
    - navigation.sections
    - search.suggest

plugins:
  - search:
      lang: ja
  - awesome-pages # 各フォルダーの .pages でメニューの名前と順番を決める

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true

validation:
  links:
    not_found: warn
    anchors: warn
