site_name: おやさいサーバー Wiki
site_url: https://wiki.oyasai.io/
docs_dir: docs

theme:
  name: material
  language: ja
  logo: assets/logo.svg
  favicon: assets/logo.svg
  font:
    text: M PLUS Rounded 1c
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: ダークモードにする
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: ライトモードにする
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight

extra_css:
  - assets/extra.css

plugins:
  - search:
      lang: ja
  - awesome-pages # 各フォルダーの .pages でメニューの名前と順番を決める

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - nl2br
  - tables
  - toc:
      permalink: true

validation:
  links:
    not_found: warn
    anchors: warn
