# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Wiki How-to
  items:
    - label: 'Wiki編集（GitHub ver.）'
      link: '/wiki/howto'
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
